export const PROFESSIONS = [
    "Alchimiste",
    "Bijoutier",
    "Bricoleur",
    "Bûcheron",
    "Chasseur",
    "Cordonnier",
    "Façonneur",
    "Forgeron",
    "Mineur",
    "Paysan",
    "Pêcheur",
    "Sculpteur",
    "Tailleur",
].sort();
